site_name: Jackson Docs
theme:
    name: 'material'
nav: 
    - Home: 'index.md'
    - 学习Markdown: 
        - Markdown快速开始: ./a/a_10001.md
        - Markdown徽章: ./a/a_10002.md
        - Markdown进阶: ./a/a_10003.md
    - Python: 
        - 基础语法: ./b/b_10001.md
        - 进阶语法: ./b/b_10002.md
        - 常用方法: ./b/b_10003.md
    - Go: ./c/c_10000.md
    - Linux: ./d/d_10000.md
    - 测试专业: 
        - 测试基础: ./e/e_10001.md
        - 自动化测试: ./e/e_10002.md
        - 性能测试: ./e/e_10003.md
    - Git: ./f/f_10000.md
    - 读书笔记: 
        - 我的书单: ./g/g_10001.md
        - 单核工作法图解: ./g/g_10002.md
        - 高效读书的习惯: ./g/g_10003.md
    - 金融理财: ./h/h_10000.md
    - About: about.md
